apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: robot-shop
    meta.helm.sh/release-namespace: robot-shop
  creationTimestamp: "2021-05-13T09:57:16Z"
  generation: 4
  labels:
    app.kubernetes.io/managed-by: Helm
    service: shipping
  name: shipping
  namespace: robot-shop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: shipping
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: shipping
    spec:
      containers:
      - image: docker.io/jxadro/shipping:1.0
        imagePullPolicy: IfNotPresent
        name: shipping
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: "/dump"
          name: dump          
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dump
        persistentVolumeClaim:
          claimName: dump
