apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dump
  namespace: robot-shop
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
